server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy für die Dashboard-API
    location /api/config {
        proxy_pass http://dashboard-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy für Uptime Kuma API & WebSockets
    location /api/kuma/ {
        # Schneidet "/api/kuma" vor der Weiterleitung ab
        rewrite ^/api/kuma/(.*) /$1 break;

        proxy_pass http://uptime-kuma:3001;

        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}