FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY scripts ./scripts
COPY entry.env ./entry.env

# Das Skript läuft direkt dauerhaft durch und lauscht auf Dateiänderungen
CMD ["node", "scripts/sync-kuma.js"]