FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

# Kopiert den Ordner scripts/ nach /app/scripts/
COPY scripts ./scripts
COPY entry.env ./entry.env

# Startet das Script im Ordner scripts/
CMD ["node", "scripts/sync-kuma.js"]